"""Tests for tools/skills."""

from __future__ import annotations

import importlib.util
import shutil
import sys
import uuid
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
SCRIPT_PATH = ROOT / "tools" / "skills" / "__init__.py"


def load_sync_skills():
    spec = importlib.util.spec_from_file_location("sync_skills", SCRIPT_PATH)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules["sync_skills"] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture
def sync_skills():
    return load_sync_skills()


@pytest.fixture
def repo():
    # Use a workspace-local temp dir so sandboxed test runs can create `.cursor/`.
    base = ROOT / "tests" / "_sync_tmp"
    base.mkdir(exist_ok=True)
    repo_path = base / f"repo-{uuid.uuid4().hex}"
    repo_path.mkdir()
    source = repo_path / ".ai" / "skills"
    source.mkdir(parents=True)
    (source / "testing.md").write_text(
        "---\n"
        "name: testing\n"
        "description: Use this skill when writing tests.\n"
        "---\n\n"
        "# Skill: Testing\n\n"
        "Canonical testing guidance lives here.\n"
    )
    roles = repo_path / ".ai" / "roles"
    roles.mkdir()
    (roles / "reviewer.md").write_text(
        "---\n"
        "name: reviewer\n"
        "description: Review changes.\n"
        "---\n\n"
        "# Role: Reviewer\n\n"
        "Canonical reviewer guidance lives here.\n"
    )
    workflows = repo_path / ".ai" / "workflows"
    workflows.mkdir()
    (workflows / "feature-task.md").write_text(
        "# Workflow: Feature Task\n\nCanonical workflow guidance lives here.\n"
    )
    yield repo_path
    shutil.rmtree(repo_path, ignore_errors=True)


def test_generates_claude_cursor_and_codex_adapters(sync_skills, repo: Path) -> None:
    sync_skills.sync(repo)

    claude = repo / ".claude" / "skills" / "testing" / "SKILL.md"
    cursor = repo / ".cursor" / "rules" / "skills" / "testing.mdc"
    codex = repo / ".codex" / "skills" / "testing.md"
    claude_role = repo / ".claude" / "agents" / "reviewer.md"
    cursor_role = repo / ".cursor" / "rules" / "roles" / "reviewer.mdc"
    codex_role = repo / ".codex" / "agents" / "reviewer.md"
    claude_workflow = repo / ".claude" / "workflows" / "feature-task.md"
    cursor_workflow = repo / ".cursor" / "rules" / "workflows" / "feature-task.mdc"
    codex_workflow = repo / ".codex" / "workflows" / "feature-task.md"

    assert claude.exists()
    assert cursor.exists()
    assert codex.exists()
    assert claude_role.exists()
    assert cursor_role.exists()
    assert codex_role.exists()
    assert claude_workflow.exists()
    assert cursor_workflow.exists()
    assert codex_workflow.exists()


def test_generated_adapters_include_full_skill_body(sync_skills, repo: Path) -> None:
    sync_skills.sync(repo)

    claude = (repo / ".claude" / "skills" / "testing" / "SKILL.md").read_text()
    cursor = (repo / ".cursor" / "rules" / "skills" / "testing.mdc").read_text()
    codex = (repo / ".codex" / "skills" / "testing.md").read_text()

    for content in (claude, cursor, codex):
        assert "# Skill: Testing" in content
        assert "Canonical testing guidance lives here." in content
        assert "generated: true" in content
        assert "source: .ai/skills/testing.md" in content
        assert "Do not edit this file directly." in content
        assert "Read and apply `.ai/skills/testing.md`." not in content
        assert "# Skill Pointer:" not in content

    role = (repo / ".codex" / "agents" / "reviewer.md").read_text()
    workflow = (repo / ".cursor" / "rules" / "workflows" / "feature-task.mdc").read_text()
    assert "# Role: Reviewer" in role
    assert "source: .ai/roles/reviewer.md" in role
    assert "# Workflow: Feature Task" in workflow
    assert "source: .ai/workflows/feature-task.md" in workflow


def test_source_frontmatter_not_duplicated_in_generated_body(sync_skills, repo: Path) -> None:
    sync_skills.sync(repo)

    claude = (repo / ".claude" / "skills" / "testing" / "SKILL.md").read_text()
    _, body = sync_skills.split_skill_content(claude)

    assert "# Skill: Testing" in body
    assert "Canonical testing guidance lives here." in body
    assert "description: Use this skill when writing tests." not in body
    assert body.count("---") == 0


def test_is_generated_reads_frontmatter_marker(sync_skills, tmp_path: Path) -> None:
    generated_file = tmp_path / "generated.md"
    manual_file = tmp_path / "manual.md"

    generated_file.write_text("---\nname: x\ngenerated: true\n---\n")
    manual_file.write_text("---\nname: x\ndescription: manual\n---\n")

    assert sync_skills.is_generated(generated_file) is True

    generated_quoted = tmp_path / "generated-quoted.md"
    generated_quoted.write_text('---\nname: x\ngenerated: "true"\n---\n')
    assert sync_skills.is_generated(generated_quoted) is True
    assert sync_skills.is_generated(manual_file) is False


def test_removes_stale_generated_adapters(sync_skills, repo: Path) -> None:
    sync_skills.sync(repo)

    stale_claude_dir = repo / ".claude" / "skills" / "old-skill"
    stale_claude_dir.mkdir(parents=True)
    (stale_claude_dir / "SKILL.md").write_text(
        "---\nname: old-skill\ngenerated: true\nsource: .ai/skills/old-skill.md\n---\n"
    )
    stale_flat = repo / ".claude" / "skills" / "legacy.md"
    stale_flat.write_text("---\nname: legacy\ngenerated: true\n---\n")
    stale_cursor = repo / ".cursor" / "rules" / "old-skill.mdc"
    stale_cursor.write_text("---\ngenerated: true\n---\n")
    stale_codex = repo / ".codex" / "skills" / "old-skill.md"
    stale_codex.write_text("---\nname: old-skill\ngenerated: true\n---\n")

    sync_skills.sync(repo)

    assert not stale_claude_dir.exists()
    assert not stale_flat.exists()
    assert not stale_cursor.exists()
    assert not stale_codex.exists()


def test_does_not_remove_manual_non_generated_files(sync_skills, repo: Path) -> None:
    manual_rule = repo / ".cursor" / "rules" / "project.mdc"
    manual_rule.parent.mkdir(parents=True, exist_ok=True)
    manual_rule.write_text(
        "---\n"
        "description: Project-wide AI instructions\n"
        "alwaysApply: true\n"
        "---\n\n"
        "Manual project adapter.\n"
    )

    sync_skills.sync(repo)

    assert manual_rule.exists()
    assert "Manual project adapter." in manual_rule.read_text()


def test_removes_legacy_flat_claude_files(sync_skills, repo: Path) -> None:
    legacy = repo / ".claude" / "skills" / "testing.md"
    legacy.parent.mkdir(parents=True, exist_ok=True)
    legacy.write_text("---\nname: testing\ngenerated: true\n---\n")

    sync_skills.sync(repo)

    assert not legacy.exists()
    assert (repo / ".claude" / "skills" / "testing" / "SKILL.md").exists()


def test_uses_file_stem_and_fallback_description(sync_skills, repo: Path) -> None:
    (repo / ".ai" / "skills" / "no-frontmatter.md").write_text("# Skill without frontmatter\n")

    sync_skills.sync(repo)

    claude = repo / ".claude" / "skills" / "no-frontmatter" / "SKILL.md"
    assert claude.exists()
    content = claude.read_text()
    assert "Use this skill for no-frontmatter related work." in content
    assert "# Skill without frontmatter" in content
