#!/usr/bin/env python3
"""Generate tool-specific skill adapters from .ai/skills/.

Run: python scripts/sync_skills.py
Generates full skill adapters for Claude Code, Cursor, and Codex.
.ai/skills/ is the single source of truth — edit there, never in the adapters.

Adapter locations:
  .claude/skills/<name>/SKILL.md  — Claude Code skills
  .cursor/rules/<name>.mdc        — Cursor agent-requested rules
  .codex/skills/<name>.md         — Codex skills
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
SOURCE = ROOT / ".ai" / "skills"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---(?:\n|$)", re.DOTALL)

FALLBACK_DESCRIPTION = "Use this skill for {name} related work."

GENERATED_COMMENT = """\
<!--
This file is generated by scripts/sync_skills.py.
Do not edit this file directly.
Edit .ai/skills/{name}.md and run `make sync-skills`.
-->
"""

CLAUDE_HEADER = """\
---
name: {name}
description: {description}
generated: true
source: .ai/skills/{name}.md
---
"""

CURSOR_HEADER = """\
---
description: {description}
alwaysApply: false
generated: true
source: .ai/skills/{name}.md
---
"""

CODEX_HEADER = """\
---
name: {name}
description: {description}
generated: true
source: .ai/skills/{name}.md
---
"""


def parse_frontmatter_block(block: str) -> dict[str, object]:
    """Parse YAML frontmatter key/value pairs."""
    fields: dict[str, object] = {}
    for line in block.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or ":" not in stripped:
            continue
        key, _, raw_value = stripped.partition(":")
        key = key.strip()
        value = raw_value.strip()
        if not key:
            continue

        if (value.startswith('"') and value.endswith('"')) or (
            value.startswith("'") and value.endswith("'")
        ):
            value = value[1:-1]

        lowered = value.lower()
        if lowered == "true":
            fields[key] = True
        elif lowered == "false":
            fields[key] = False
        else:
            fields[key] = value

    return fields


def split_skill_content(text: str) -> tuple[dict[str, object], str]:
    """Return frontmatter fields and body without source frontmatter."""
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text

    fields = parse_frontmatter_block(match.group(1))
    body = text[match.end() :]
    if body.startswith("\n"):
        body = body[1:]
    return fields, body


def read_source_skill(path: Path) -> tuple[str, str, str]:
    """Return skill name, description, and body for a canonical skill file."""
    text = path.read_text()
    fields, body = split_skill_content(text)
    name = str(fields.get("name") or path.stem)
    description = str(fields.get("description") or FALLBACK_DESCRIPTION.format(name=name))
    return name, description, body


def parse_frontmatter(text: str) -> dict[str, object]:
    """Parse YAML frontmatter from file text."""
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}
    return parse_frontmatter_block(match.group(1))


def is_generated(path: Path) -> bool:
    try:
        generated = parse_frontmatter(path.read_text()).get("generated")
    except OSError:
        return False

    if generated is True:
        return True
    return isinstance(generated, str) and generated.lower() == "true"


def yaml_scalar(value: str) -> str:
    """Return a YAML-safe scalar for frontmatter fields."""
    if not value:
        return '""'
    if re.search(r'[:#\[\]{}"\'\\,&*!|>%@`]', value) or value.strip() != value:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


def build_adapter(header: str, *, name: str, description: str, body: str) -> str:
    comment = GENERATED_COMMENT.format(name=name)
    rendered_header = header.format(name=name, description=yaml_scalar(description))
    if body:
        return f"{rendered_header}\n{comment}\n{body}"
    return f"{rendered_header}\n{comment}\n"


def write_adapter(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def generate_adapters(
    root: Path,
    *,
    generated: list[Path],
) -> set[str]:
    source_dir = root / ".ai" / "skills"
    claude_dir = root / ".claude" / "skills"
    cursor_dir = root / ".cursor" / "rules"
    codex_dir = root / ".codex" / "skills"

    source_names: set[str] = set()

    for skill in sorted(source_dir.glob("*.md")):
        name, description, body = read_source_skill(skill)
        source_names.add(name)

        claude_path = claude_dir / name / "SKILL.md"
        write_adapter(
            claude_path,
            build_adapter(CLAUDE_HEADER, name=name, description=description, body=body),
        )
        generated.append(claude_path)

        cursor_path = cursor_dir / f"{name}.mdc"
        write_adapter(
            cursor_path,
            build_adapter(CURSOR_HEADER, name=name, description=description, body=body),
        )
        generated.append(cursor_path)

        codex_path = codex_dir / f"{name}.md"
        write_adapter(
            codex_path,
            build_adapter(CODEX_HEADER, name=name, description=description, body=body),
        )
        generated.append(codex_path)

    return source_names


def remove_stale_adapters(
    root: Path,
    source_names: set[str],
    *,
    removed: list[Path],
) -> None:
    claude_dir = root / ".claude" / "skills"
    cursor_dir = root / ".cursor" / "rules"
    codex_dir = root / ".codex" / "skills"

    if claude_dir.exists():
        for flat_file in claude_dir.glob("*.md"):
            if not is_generated(flat_file):
                continue
            # Legacy flat layout: .claude/skills/<name>.md (replaced by <name>/SKILL.md).
            flat_file.unlink()
            removed.append(flat_file)

        for skill_dir in claude_dir.iterdir():
            if not skill_dir.is_dir():
                continue
            skill_file = skill_dir / "SKILL.md"
            if skill_dir.name not in source_names and skill_file.exists() and is_generated(skill_file):
                skill_file.unlink()
                removed.append(skill_file)
                if not any(skill_dir.iterdir()):
                    skill_dir.rmdir()
                    removed.append(skill_dir)

    if cursor_dir.exists():
        for rule_file in cursor_dir.glob("*.mdc"):
            if rule_file.stem not in source_names and is_generated(rule_file):
                rule_file.unlink()
                removed.append(rule_file)

    if codex_dir.exists():
        for skill_file in codex_dir.glob("*.md"):
            if skill_file.stem not in source_names and is_generated(skill_file):
                skill_file.unlink()
                removed.append(skill_file)


def sync(root: Path | None = None) -> int:
    root = root or ROOT
    generated: list[Path] = []
    removed: list[Path] = []

    source_names = generate_adapters(root, generated=generated)
    remove_stale_adapters(root, source_names, removed=removed)

    print(f"synced {len(source_names)} skill(s)")
    print(f"  generated {len(generated)} adapter(s)")
    for path in sorted(generated, key=lambda p: str(p.relative_to(root))):
        print(f"    + {path.relative_to(root)}")

    if removed:
        print(f"  removed {len(removed)} stale adapter(s)")
        for path in sorted(removed, key=lambda p: str(p.relative_to(root))):
            print(f"    - {path.relative_to(root)}")

    print("targets:")
    print("  .claude/skills/<name>/SKILL.md")
    print("  .cursor/rules/<name>.mdc")
    print("  .codex/skills/<name>.md")

    return 0


if __name__ == "__main__":
    sys.exit(sync())
