#!/usr/bin/env python3
"""Generate tool-specific AI instruction adapters from .ai/.

.ai/ is the single source of truth. Edit canonical files there, then run:

    make generate-ai              # all targets
    make generate-ai TARGET=claude
    make generate-ai TARGET=codex

Each target reads .ai/skills/, .ai/roles/, and .ai/workflows/ and writes
adapted files into the appropriate tool folder.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import Protocol

ROOT = Path(__file__).parent.parent.parent

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---(?:\n|$)", re.DOTALL)

FALLBACK_DESCRIPTION = "Use this {kind} for {name} related work."

GENERATED_COMMENT = """\
<!--
This file is generated by tools/skills.
Do not edit this file directly.
Edit .ai/{source_kind}/{name}.md and run `make generate-ai`.
-->
"""

MARKDOWN_HEADER = """\
---
name: {name}
description: {description}
generated: true
source: .ai/{source_kind}/{name}.md
---
"""

SOURCE_KINDS: dict[str, str] = {
    "skills": "skill",
    "roles": "role",
    "workflows": "workflow",
}


# ---------------------------------------------------------------------------
# Frontmatter helpers
# ---------------------------------------------------------------------------


def _parse_frontmatter_block(block: str) -> dict[str, object]:
    fields: dict[str, object] = {}
    for line in block.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or ":" not in stripped:
            continue
        key, _, raw_value = stripped.partition(":")
        key = key.strip()
        value = raw_value.strip()
        if not key:
            continue
        if (value.startswith('"') and value.endswith('"')) or (
            value.startswith("'") and value.endswith("'")
        ):
            value = value[1:-1]
        lowered = value.lower()
        if lowered == "true":
            fields[key] = True
        elif lowered == "false":
            fields[key] = False
        else:
            fields[key] = value
    return fields


def split_instruction_content(text: str) -> tuple[dict[str, object], str]:
    """Return frontmatter fields and body (without the source frontmatter block)."""
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text
    fields = _parse_frontmatter_block(match.group(1))
    body = text[match.end():]
    if body.startswith("\n"):
        body = body[1:]
    return fields, body


# Backward-compatible alias used by existing tests.
split_skill_content = split_instruction_content


def parse_frontmatter(text: str) -> dict[str, object]:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}
    return _parse_frontmatter_block(match.group(1))


def is_generated(path: Path) -> bool:
    try:
        generated = parse_frontmatter(path.read_text()).get("generated")
    except OSError:
        return False
    if generated is True:
        return True
    return isinstance(generated, str) and generated.lower() == "true"


def yaml_scalar(value: str) -> str:
    if not value:
        return '""'
    if re.search(r'[:#\[\]{}"\'\\,&*!|>%@`]', value) or value.strip() != value:
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


# ---------------------------------------------------------------------------
# Source reader
# ---------------------------------------------------------------------------


def read_source(path: Path, *, kind: str) -> tuple[str, str, str]:
    """Return (name, description, body) for a canonical .ai/ instruction file."""
    text = path.read_text()
    fields, body = split_instruction_content(text)
    name = str(fields.get("name") or path.stem)
    description = str(
        fields.get("description") or FALLBACK_DESCRIPTION.format(kind=kind, name=name)
    )
    return name, description, body


def build_adapter(header: str, *, name: str, description: str, body: str, source_kind: str) -> str:
    comment = GENERATED_COMMENT.format(name=name, source_kind=source_kind)
    rendered_header = header.format(
        name=name,
        description=yaml_scalar(description),
        source_kind=source_kind,
    )
    if body:
        return f"{rendered_header}\n{comment}\n{body}"
    return f"{rendered_header}\n{comment}\n"


def write_adapter(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def remove_generated(path: Path, removed: list[Path]) -> None:
    if is_generated(path):
        path.unlink()
        removed.append(path)


def remove_if_empty(path: Path, removed: list[Path]) -> None:
    if path.exists() and path.is_dir() and not any(path.iterdir()):
        path.rmdir()
        removed.append(path)


def remove_stale_in(
    adapter_dir: Path, source_names: set[str], removed: list[Path]
) -> None:
    if not adapter_dir.exists():
        return
    for f in list(adapter_dir.glob("*.md")) + list(adapter_dir.glob("*.mdc")):
        if f.stem not in source_names:
            remove_generated(f, removed)


# ---------------------------------------------------------------------------
# Target protocol and implementations
# ---------------------------------------------------------------------------


class Target(Protocol):
    name: str

    def generate(
        self, root: Path, source_kind: str, ai_name: str, description: str, body: str
    ) -> Path: ...

    def remove_stale(
        self, root: Path, source_names_by_kind: dict[str, set[str]], removed: list[Path]
    ) -> None: ...

    def delete(self, root: Path, deleted: list[Path]) -> None: ...


class ClaudeTarget:
    name = "claude"

    def generate(
        self, root: Path, source_kind: str, ai_name: str, description: str, body: str
    ) -> Path:
        if source_kind == "skills":
            path = root / ".claude" / "skills" / ai_name / "SKILL.md"
        elif source_kind == "roles":
            path = root / ".claude" / "agents" / f"{ai_name}.md"
        else:
            path = root / ".claude" / "workflows" / f"{ai_name}.md"
        write_adapter(
            path,
            build_adapter(
                MARKDOWN_HEADER,
                name=ai_name,
                description=description,
                body=body,
                source_kind=source_kind,
            ),
        )
        return path

    def remove_stale(
        self, root: Path, source_names_by_kind: dict[str, set[str]], removed: list[Path]
    ) -> None:
        skill_names = source_names_by_kind.get("skills", set())
        skills_dir = root / ".claude" / "skills"
        if skills_dir.exists():
            for f in skills_dir.glob("*.md"):  # legacy flat files
                remove_generated(f, removed)
            for skill_dir in skills_dir.iterdir():
                if not skill_dir.is_dir():
                    continue
                skill_file = skill_dir / "SKILL.md"
                if skill_dir.name not in skill_names and skill_file.exists():
                    remove_generated(skill_file, removed)
                    remove_if_empty(skill_dir, removed)

        remove_stale_in(
            root / ".claude" / "agents", source_names_by_kind.get("roles", set()), removed
        )
        remove_stale_in(
            root / ".claude" / "workflows", source_names_by_kind.get("workflows", set()), removed
        )

    def delete(self, root: Path, deleted: list[Path]) -> None:
        for subdir in ("skills", "agents", "workflows"):
            delete_dir(root / ".claude" / subdir, deleted)


class CodexTarget:
    name = "codex"

    def _adapter_subdir(self, source_kind: str) -> str:
        return "agents" if source_kind == "roles" else source_kind

    def generate(
        self, root: Path, source_kind: str, ai_name: str, description: str, body: str
    ) -> Path:
        path = root / ".codex" / self._adapter_subdir(source_kind) / f"{ai_name}.md"
        write_adapter(
            path,
            build_adapter(
                MARKDOWN_HEADER,
                name=ai_name,
                description=description,
                body=body,
                source_kind=source_kind,
            ),
        )
        return path

    def remove_stale(
        self, root: Path, source_names_by_kind: dict[str, set[str]], removed: list[Path]
    ) -> None:
        remove_stale_in(
            root / ".codex" / "skills", source_names_by_kind.get("skills", set()), removed
        )
        remove_stale_in(
            root / ".codex" / "agents", source_names_by_kind.get("roles", set()), removed
        )
        remove_stale_in(
            root / ".codex" / "workflows", source_names_by_kind.get("workflows", set()), removed
        )


# Registry — add new targets here.
TARGETS: dict[str, ClaudeTarget | CodexTarget] = {
    "claude": ClaudeTarget(),
    "codex": CodexTarget(),
}


# ---------------------------------------------------------------------------
# Core sync logic
# ---------------------------------------------------------------------------


def sync(
    root: Path | None = None,
    *,
    targets: list[str] | None = None,
) -> int:
    """Generate adapters. targets=None means all registered targets."""
    root = root or ROOT

    active_targets = (
        [TARGETS[t] for t in targets if t in TARGETS]
        if targets
        else list(TARGETS.values())
    )

    if not active_targets:
        known = ", ".join(TARGETS)
        print(f"error: unknown target(s). Known targets: {known}", file=sys.stderr)
        return 1

    generated: list[Path] = []
    removed: list[Path] = []
    source_names_by_kind: dict[str, set[str]] = {}

    for source_kind, kind_label in SOURCE_KINDS.items():
        source_dir = root / ".ai" / source_kind
        names: set[str] = set()
        for source_file in sorted(source_dir.glob("*.md")):
            ai_name, description, body = read_source(source_file, kind=kind_label)
            names.add(ai_name)
            for target in active_targets:
                path = target.generate(root, source_kind, ai_name, description, body)
                generated.append(path)
        source_names_by_kind[source_kind] = names

    for target in active_targets:
        target.remove_stale(root, source_names_by_kind, removed)

    target_names = ", ".join(t.name for t in active_targets)
    total_sources = sum(len(v) for v in source_names_by_kind.values())
    print(f"generated {len(generated)} adapter(s) for [{target_names}] from {total_sources} source(s)")
    for path in sorted(generated, key=lambda p: str(p.relative_to(root))):
        print(f"  + {path.relative_to(root)}")
    if removed:
        print(f"removed {len(removed)} stale adapter(s)")
        for path in sorted(removed, key=lambda p: str(p.relative_to(root))):
            print(f"  - {path.relative_to(root)}")

    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate tool adapters from .ai/ (single source of truth).",
    )
    parser.add_argument(
        "--target",
        metavar="NAME",
        action="append",
        dest="targets",
        help=f"target to generate (choices: {', '.join(TARGETS)}); repeat for multiple; omit for all",
    )
    args = parser.parse_args(argv)
    return sync(targets=args.targets)


if __name__ == "__main__":
    sys.exit(main())
